<a href="https://colab.research.google.com/github/Jionary/Repository-IA/blob/main/An%C3%A1lisis_estad%C3%ADstico_de_calidad_del_aire_de_la_CDMX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as pls
import seaborn as sns

#Exploración inicial

In [14]:
df_2026 = pd.read_csv(
    "contaminantes_2026.csv",
    skiprows = 9
)

print(f"Información inicial: {df_2026.info()}")
print(f"Filas: {df_2026.shape[0]}")
print(f"Columnas: {df_2026.shape[1]}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433296 entries, 0 to 433295
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          433296 non-null  object
 1   id_station    433296 non-null  object
 2   id_parameter  433296 non-null  object
 3   valor         208323 non-null  float64
 4   unit          80784 non-null   float64
dtypes: float64(2), object(3)
memory usage: 16.5+ MB
Información inicial: None
Filas: 433296
Columnas: 5

In [15]:
df_2026.head()

                  date id_station id_parameter  valor  unit
0  2026-01-01 00:00:00        ACO           CO    NaN   NaN
1  2026-01-01 00:00:00        ACO           NO    NaN   NaN
2  2026-01-01 00:00:00        ACO          NO2    NaN   NaN
3  2026-01-01 00:00:00        ACO          NOX    NaN   NaN
4  2026-01-01 00:00:00        ACO           O3    NaN   NaN

In [16]:
df_2026.tail()

                       date id_station id_parameter  valor  unit
433291  2026-02-28 23:00:00        XAL           O3    NaN   1.0
433292  2026-02-28 23:00:00        XAL         PM10    NaN   2.0
433293  2026-02-28 23:00:00        XAL        PM2.5    NaN   2.0
433294  2026-02-28 23:00:00        XAL         PMCO    NaN   2.0
433295  2026-02-28 23:00:00        XAL          SO2    NaN   1.0

#EDA Inicial
Exploración de nulos y duplicados

In [19]:
print(f"Nulos: {df_2026.isnull().sum()}")
print(f"Duplicados: {df_2026.duplicated().sum()}")

Nulos: date                 0
id_station           0
id_parameter         0
valor           224973
unit            352512
dtype: int64
Duplicados: 0